[project]
name = "temps"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.0",
    "inquirerpy>=0.3.4",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
]

[[tool.uv.index]]
url = "https://artifactory.bayer.com/artifactory/api/pypi/veeva-pypi-all-libraries/simple"
